### PR TITLE
Rename fork

### PR DESCRIPTION
**Pull request by txtsd**

### CODE REVIEW

**Comment by aminvakil** [comment]
cc @alerque

**Comment by txtsd** [comment]
Made an accident. Got 2 stars. Nice.

**Comment by aminvakil** [comment]
I mentioned Caleb as they were trying to find a way for this project to go on in https://github.com/eli-schwartz/aurpublish/issues/24, but nice :)

**Comment by eli-schwartz** [comment]
Hi, sorry -- I'm not sure why I didn't notice that issue, it may have been when I declared bankruptcy on github notifications? (I have a separate filter for PRs anyways...)

Aside: it is not obvious to me what actual concrete changes are being made here, other than adding a dinosaur theme.

**Comment by aminvakil** [comment]
Hi @eli-schwartz , I'm very happy to hear from you after a long time!

So what do you think about it? There are other PRs open, which I don't know if they need to be changed or something else, also there are open issues.

I'm glad to be able to help too, although I'm not a TU (or Package maintainer these days).

**Comment by txtsd** [comment]
It's just the initial release. I'm trying to [`release early, release often`](https://en.wikipedia.org/wiki/Release_early,_release_often).  It's opinionated atm, but it will let users configure the commit message templates and remotes, among other things.

**Comment by alerque** [comment]
The dinosaur theme is amusing and if we *had to* fork it might work, but I would **really** rather not have the project renamed at all. As mentioned in #24 I would prefer if we could just run with the current name and pickup existing issues and PRs where they are. @eli-schwartz if my comments in #24 got messed too would you please consider adding me as a maintainer of this repo (and optionally asking me to then transfer this to my namespace if you'd like the future changes to be out of your namespace)? I'm already the maintainer of the package in the [extra] repo and have considered pointing that to a fork, but have believed it would be more respectful/transparent to you and the project origins if we could keep this as the canonical repository. Thanks for your consideration.

**Pull request closed without merging**
